# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180605_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='column',
        ),
    ]
