# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180605_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='网址'),
        ),
    ]
